FROM ubuntu:20.04

WORKDIR /root

ADD main  main

COPY config.yaml config.yaml

RUN apt-get -qq update \
    && apt-get -qq install -y --no-install-recommends ca-certificates curl

EXPOSE 8081

ENTRYPOINT  ["./main"]
